//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Exception.
        /// </summary>
        internal static string ChatForm_Chat_Exception {
            get {
                return ResourceManager.GetString("ChatForm_Chat_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatroom.
        /// </summary>
        internal static string ChatForm_Chatroom {
            get {
                return ResourceManager.GetString("ChatForm_Chatroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string ChatForm_joinLeaveBtn_Click_Leave {
            get {
                return ResourceManager.GetString("ChatForm_joinLeaveBtn_Click_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick cannot be empty.
        /// </summary>
        internal static string ChatForm_joinLeaveBtn_Click_Nick_cannot_be_empty {
            get {
                return ResourceManager.GetString("ChatForm_joinLeaveBtn_Click_Nick_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic cannot be empty.
        /// </summary>
        internal static string ChatForm_joinLeaveBtn_Click_Topic_cannot_be_empty {
            get {
                return ResourceManager.GetString("ChatForm_joinLeaveBtn_Click_Topic_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string ChatForm_LeaveRoom_Join {
            get {
                return ResourceManager.GetString("ChatForm_LeaveRoom_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatroom participants.
        /// </summary>
        internal static string ChatForm_showParticipantsBtn_Click_Chatroom_participants {
            get {
                return ResourceManager.GetString("ChatForm_showParticipantsBtn_Click_Chatroom_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty or null.
        /// </summary>
        internal static string Client_Join_Cannot_be_empty_or_null {
            get {
                return ResourceManager.GetString("Client_Join_Cannot_be_empty_or_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sended.
        /// </summary>
        internal static string MessageCallback_SayCallback_Message_sended {
            get {
                return ResourceManager.GetString("MessageCallback_SayCallback_Message_sended", resourceCulture);
            }
        }
    }
}
